# Generated by Django 3.0.8 on 2020-12-30 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pic/'),
            preserve_default=False,
        ),
    ]
