# Generated by Django 3.0.8 on 2020-12-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/images/profile_pic/profile_pic.svg', upload_to='profile_pic/'),
        ),
    ]
