# Generated by Django 3.0.8 on 2020-12-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20201215_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='total_bathroom',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
