# Generated by Django 3.0.8 on 2020-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20201216_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_space',
            field=models.IntegerField(default=0),
        ),
    ]
