# Generated by Django 3.0.8 on 2020-12-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20201221_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property_Category'),
        ),
    ]
