# Generated by Django 3.0.8 on 2020-12-21 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20201221_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='college',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property_Category'),
        ),
    ]
