# Generated by Django 3.0.8 on 2020-12-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20201222_1005'),
        ('property', '0013_auto_20201221_1557'),
    ]

    operations = [
    ]
