# Generated by Django 3.0.8 on 2020-12-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20201230_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.Property_Category'),
        ),
    ]
